export interface MovieOption {
  title: string;
  year: string;
  tagline: string;
  rating: string;
}

export const GENRES = [
  'Action', 
  'Sci-Fi', 
  'Horror', 
  'Comedy', 
  'Thriller', 
  'Romance', 
  'Anime', 
  'Drama', 
  'Mystery', 
  'Fantasy',
  'Crime' // Added Crime Genre
] as const;

export type Genre = typeof GENRES[number];

export type MediaType = 'Movie' | 'Show';

// --- MOVIES DATABASE ---
export const MOVIE_DB: Record<Genre, MovieOption[]> = {
  'Action': [
    { title: "Mad Max: Fury Road", year: "2015", tagline: "What a lovely day.", rating: "⭐ 8.1" },
    { title: "The Dark Knight", year: "2008", tagline: "Why so serious?", rating: "⭐ 9.0" },
    { title: "John Wick 4", year: "2023", tagline: "No way back, one way out.", rating: "⭐ 7.7" },
    { title: "Terminator 2: Judgment Day", year: "1991", tagline: "Hasta la vista, baby.", rating: "⭐ 8.6" },
    { title: "Gladiator", year: "2000", tagline: "Father to a murdered son.", rating: "⭐ 8.5" },
    { title: "Top Gun: Maverick", year: "2022", tagline: "Feel the need... the need for speed.", rating: "⭐ 8.3" },
    { title: "Die Hard", year: "1988", tagline: "Yippee-ki-yay.", rating: "⭐ 8.2" },
    { title: "The Raid: Redemption", year: "2011", tagline: "1 Ruthless Crime Lord. 20 Elite Cops. 30 Floors of Hell.", rating: "⭐ 7.6" },
    { title: "Logan", year: "2017", tagline: "His time has come.", rating: "⭐ 8.1" },
    { title: "Avengers: Infinity War", year: "2018", tagline: "Destiny arrives all the same.", rating: "⭐ 8.4" },
    { title: "Kill Bill: Vol. 1", year: "2003", tagline: "Here comes the bride.", rating: "⭐ 8.2" },
    { title: "Edge of Tomorrow", year: "2014", tagline: "Live. Die. Repeat.", rating: "⭐ 7.9" },
    { title: "Heat", year: "1995", tagline: "A Los Angeles crime saga.", rating: "⭐ 8.3" },
    { title: "RRR", year: "2022", tagline: "Rise. Roar. Revolt.", rating: "⭐ 7.8" },
    { title: "Casino Royale", year: "2006", tagline: "Everyone has a past. Every legend has a beginning.", rating: "⭐ 8.0" },
    { title: "Crouching Tiger, Hidden Dragon", year: "2000", tagline: "A timeless story of strength, secrets and two warriors.", rating: "⭐ 7.9" },
    { title: "Mission: Impossible - Fallout", year: "2018", tagline: "Some missions are not a choice.", rating: "⭐ 7.7" },
    { title: "Dredd", year: "2012", tagline: "Judgment is coming.", rating: "⭐ 7.1" },
    { title: "Baby Driver", year: "2017", tagline: "All you need is one killer track.", rating: "⭐ 7.6" },
    { title: "District 9", year: "2009", tagline: "You are not welcome here.", rating: "⭐ 7.9" },
    { title: "Spider-Man: Into the Spider-Verse", year: "2018", tagline: "Anyone can wear the mask.", rating: "⭐ 8.4" },
    { title: "Leon: The Professional", year: "1994", tagline: "If you want the job done right, hire a professional.", rating: "⭐ 8.5" },
    { title: "V for Vendetta", year: "2005", tagline: "Remember, remember the 5th of November.", rating: "⭐ 8.1" },
    { title: "300", year: "2006", tagline: "Prepare for glory!", rating: "⭐ 7.6" },
    { title: "Bullet Train", year: "2022", tagline: "The end of the line is just the beginning.", rating: "⭐ 7.3" },
    { title: "Aliens", year: "1986", tagline: "This time it's war.", rating: "⭐ 8.4" },
    { title: "The Matrix", year: "1999", tagline: "Free your mind.", rating: "⭐ 8.7" },
    { title: "Seven Samurai", year: "1954", tagline: "The Mighty Warriors Who Became a Legend.", rating: "⭐ 8.6" },
    { title: "Harakiri", year: "1962", tagline: "The honor of a samurai.", rating: "⭐ 8.6" },
    { title: "Oldboy", year: "2003", tagline: "Laugh and the world laughs with you.", rating: "⭐ 8.4" },
    { title: "Hard Boiled", year: "1992", tagline: "More exciting than a dozen Die Hards.", rating: "⭐ 7.7" },
    { title: "Police Story", year: "1985", tagline: "Jackie Chan fights crime.", rating: "⭐ 7.5" },
    { title: "Ip Man", year: "2008", tagline: "A force to be reckoned with.", rating: "⭐ 8.0" },
    { title: "The Bourne Ultimatum", year: "2007", tagline: "Remember everything. Forgive nothing.", rating: "⭐ 8.0" },
    { title: "Taken", year: "2008", tagline: "I will find you, and I will kill you.", rating: "⭐ 7.8" }
  ],
  'Sci-Fi': [
    { title: "Interstellar", year: "2014", tagline: "Mankind was born on Earth. It was never meant to die here.", rating: "⭐ 8.7" },
    { title: "Blade Runner 2049", year: "2017", tagline: "More human than human.", rating: "⭐ 8.0" },
    { title: "Arrival", year: "2016", tagline: "Why are they here?", rating: "⭐ 7.9" },
    { title: "The Matrix", year: "1999", tagline: "Free your mind.", rating: "⭐ 8.7" },
    { title: "Inception", year: "2010", tagline: "Your mind is the scene of the crime.", rating: "⭐ 8.8" },
    { title: "Ex Machina", year: "2014", tagline: "To erase the line between man and machine.", rating: "⭐ 7.7" },
    { title: "Dune: Part Two", year: "2024", tagline: "Long live the fighters.", rating: "⭐ 8.6" },
    { title: "2001: A Space Odyssey", year: "1968", tagline: "The ultimate trip.", rating: "⭐ 8.3" },
    { title: "Eternal Sunshine of the Spotless Mind", year: "2004", tagline: "You can erase someone from your mind.", rating: "⭐ 8.3" },
    { title: "Her", year: "2013", tagline: "A Spike Jonze Love Story.", rating: "⭐ 8.0" },
    { title: "Minority Report", year: "2002", tagline: "Everybody runs.", rating: "⭐ 7.6" },
    { title: "Children of Men", year: "2006", tagline: "No children. No future. No hope.", rating: "⭐ 7.9" },
    { title: "The Martian", year: "2015", tagline: "Bring him home.", rating: "⭐ 8.0" },
    { title: "Moon", year: "2009", tagline: "The last man on Earth isn't alone.", rating: "⭐ 7.8" },
    { title: "Gattaca", year: "1997", tagline: "There is no gene for the human spirit.", rating: "⭐ 7.7" },
    { title: "Primer", year: "2004", tagline: "What happens if it actually works?", rating: "⭐ 6.8" },
    { title: "Annihilation", year: "2018", tagline: "Fear what's inside.", rating: "⭐ 6.8" },
    { title: "Looper", year: "2012", tagline: "Hunted by your future, haunted by your past.", rating: "⭐ 7.4" },
    { title: "Star Wars: Episode V - The Empire Strikes Back", year: "1980", tagline: "The adventure continues.", rating: "⭐ 8.7" },
    { title: "E.T. the Extra-Terrestrial", year: "1982", tagline: "He is afraid. He is alone. He is 3,000,000 light years from home.", rating: "⭐ 7.9" },
    { title: "Donnie Darko", year: "2001", tagline: "Dark. Darker. Darko.", rating: "⭐ 8.0" },
    { title: "Akira", year: "1988", tagline: "Neo-Tokyo is about to explode.", rating: "⭐ 8.0" },
    { title: "Ghost in the Shell", year: "1995", tagline: "It found a voice... Now it needs a body.", rating: "⭐ 7.9" },
    { title: "Everything Everywhere All At Once", year: "2022", tagline: "The universe is so much bigger.", rating: "⭐ 7.8" },
    { title: "Solaris", year: "1972", tagline: "There are no answers, only choices.", rating: "⭐ 8.0" },
    { title: "Stalker", year: "1979", tagline: "The Zone wants to be respected.", rating: "⭐ 8.1" },
    { title: "Metropolis", year: "1927", tagline: "There can be no understanding between the hand and the brain unless the heart acts as mediator.", rating: "⭐ 8.3" },
    { title: "Alien", year: "1979", tagline: "In space no one can hear you scream.", rating: "⭐ 8.5" },
    { title: "Back to the Future", year: "1985", tagline: "He was never in time for his classes... He wasn't in time for his dinner... Then one day... he wasn't in his time at all.", rating: "⭐ 8.5" },
    { title: "District 9", year: "2009", tagline: "You are not welcome here.", rating: "⭐ 7.9" },
    { title: "Gravity", year: "2013", tagline: "Don't let go.", rating: "⭐ 7.7" },
    { title: "Edge of Tomorrow", year: "2014", tagline: "Live. Die. Repeat.", rating: "⭐ 7.9" },
    { title: "Snowpiercer", year: "2013", tagline: "1000 people, in an iron train, blowing through the eternal winter.", rating: "⭐ 7.1" }
  ],
  'Horror': [
    { title: "Hereditary", year: "2018", tagline: "Evil runs in the family.", rating: "⭐ 7.3" },
    { title: "The Thing", year: "1982", tagline: "Man is the warmest place to hide.", rating: "⭐ 8.2" },
    { title: "Get Out", year: "2017", tagline: "Just because you're invited, doesn't mean you're welcome.", rating: "⭐ 7.8" },
    { title: "Alien", year: "1979", tagline: "In space no one can hear you scream.", rating: "⭐ 8.5" },
    { title: "The Shining", year: "1980", tagline: "He's heeere!", rating: "⭐ 8.4" },
    { title: "Midsommar", year: "2019", tagline: "Let the festivities begin.", rating: "⭐ 7.1" },
    { title: "The Witch", year: "2015", tagline: "A New-England Folktale.", rating: "⭐ 7.0" },
    { title: "Psycho", year: "1960", tagline: "Checking in?", rating: "⭐ 8.5" },
    { title: "The Silence of the Lambs", year: "1991", tagline: "To enter the mind of a killer she must challenge the mind of a madman.", rating: "⭐ 8.6" },
    { title: "It Follows", year: "2014", tagline: "It doesn't think. It doesn't feel. It doesn't give up.", rating: "⭐ 6.8" },
    { title: "Barbarian", year: "2022", tagline: "Some stay for a night. Some stay for a week. Some never leave.", rating: "⭐ 7.0" },
    { title: "Train to Busan", year: "2016", tagline: "Life or death survival begins.", rating: "⭐ 7.6" },
    { title: "28 Days Later", year: "2002", tagline: "The days are numbered.", rating: "⭐ 7.5" },
    { title: "The Conjuring", year: "2013", tagline: "Based on the true case files of the Warrens.", rating: "⭐ 7.5" },
    { title: "Sinister", year: "2012", tagline: "Once you see him, nothing can save you.", rating: "⭐ 6.8" },
    { title: "Saw", year: "2004", tagline: "Live or die. Make your choice.", rating: "⭐ 7.6" },
    { title: "A Quiet Place", year: "2018", tagline: "If they hear you, they hunt you.", rating: "⭐ 7.5" },
    { title: "Talk to Me", year: "2022", tagline: "You open the door. You let it in.", rating: "⭐ 7.1" },
    { title: "Us", year: "2019", tagline: "Watch yourself.", rating: "⭐ 6.8" },
    { title: "Nope", year: "2022", tagline: "What's a bad miracle?", rating: "⭐ 6.8" },
    { title: "Halloween", year: "1978", tagline: "The Night He Came Home!", rating: "⭐ 7.7" },
    { title: "Scream", year: "1996", tagline: "Do you like scary movies?", rating: "⭐ 7.4" },
    { title: "The Cabin in the Woods", year: "2011", tagline: "You think you know the story.", rating: "⭐ 7.0" },
    { title: "Rec", year: "2007", tagline: "Experience the fear.", rating: "⭐ 7.4" },
    { title: "The Babadook", year: "2014", tagline: "If it's in a word, or it's in a look, you can't get rid of the Babadook.", rating: "⭐ 6.8" },
    { title: "The Exorcist", year: "1973", tagline: "Something beyond comprehension is happening to a girl on this street.", rating: "⭐ 8.1" },
    { title: "Rosemary's Baby", year: "1968", tagline: "Pray for Rosemary's Baby.", rating: "⭐ 8.0" },
    { title: "Let the Right One In", year: "2008", tagline: "Eli is 12 years old. She's been 12 for over 200 years.", rating: "⭐ 7.9" },
    { title: "The Others", year: "2001", tagline: "Sooner or later, they will find you.", rating: "⭐ 7.6" },
    { title: "It", year: "2017", tagline: "You'll float too.", rating: "⭐ 7.3" },
    { title: "Evil Dead II", year: "1987", tagline: "Kiss your nerves goodbye.", rating: "⭐ 7.7" },
    { title: "Texas Chain Saw Massacre", year: "1974", tagline: "Who will survive and what will be left of them?", rating: "⭐ 7.4" },
    { title: "Suspiria", year: "1977", tagline: "The only thing more terrifying than the last 12 minutes of this film are the first 92.", rating: "⭐ 7.3" }
  ],
  'Comedy': [
    { title: "Superbad", year: "2007", tagline: "It's time to get the party started.", rating: "⭐ 7.6" },
    { title: "The Grand Budapest Hotel", year: "2014", tagline: "A murder case of Madame D.", rating: "⭐ 8.1" },
    { title: "Monty Python and the Holy Grail", year: "1975", tagline: "And now for something completely different.", rating: "⭐ 8.2" },
    { title: "Shaun of the Dead", year: "2004", tagline: "A romantic comedy. With zombies.", rating: "⭐ 7.9" },
    { title: "Mean Girls", year: "2004", tagline: "Watch your back.", rating: "⭐ 7.1" },
    { title: "Game Night", year: "2018", tagline: "This is not a game.", rating: "⭐ 6.9" },
    { title: "Palm Springs", year: "2020", tagline: "Live like there's no tomorrow.", rating: "⭐ 7.4" },
    { title: "The Big Lebowski", year: "1998", tagline: "Her life was in their hands. Now her toe is in the mail.", rating: "⭐ 8.1" },
    { title: "Hot Fuzz", year: "2007", tagline: "Big cops. Small town. Moderate violence.", rating: "⭐ 7.8" },
    { title: "What We Do in the Shadows", year: "2014", tagline: "Some interviews with some vampires.", rating: "⭐ 7.6" },
    { title: "Tropic Thunder", year: "2008", tagline: "Get some.", rating: "⭐ 7.1" },
    { title: "Step Brothers", year: "2008", tagline: "They wouldn't last a day without each other.", rating: "⭐ 6.9" },
    { title: "Knives Out", year: "2019", tagline: "Nothing brings a family together like murder.", rating: "⭐ 7.9" },
    { title: "Borat", year: "2006", tagline: "Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.", rating: "⭐ 7.4" },
    { title: "Office Space", year: "1999", tagline: "Work sucks.", rating: "⭐ 7.6" },
    { title: "21 Jump Street", year: "2012", tagline: "The only thing getting blown tonight is their cover.", rating: "⭐ 7.2" },
    { title: "The Nice Guys", year: "2016", tagline: "They're not that nice.", rating: "⭐ 7.3" },
    { title: "Ferris Bueller's Day Off", year: "1986", tagline: "One man's struggle to take it easy.", rating: "⭐ 7.8" },
    { title: "Groundhog Day", year: "1993", tagline: "He's having the day of his life... over and over again.", rating: "⭐ 8.0" },
    { title: "Dumb and Dumber", year: "1994", tagline: "For Harry and Lloyd every day is a no-brainer.", rating: "⭐ 7.3" },
    { title: "Zombieland", year: "2009", tagline: "Nut up or shut up.", rating: "⭐ 7.5" },
    { title: "Crazy, Stupid, Love.", year: "2011", tagline: "This is what crazy looks like.", rating: "⭐ 7.4" },
    { title: "School of Rock", year: "2003", tagline: "He's looking for a few good kids.", rating: "⭐ 7.2" },
    { title: "Jojo Rabbit", year: "2019", tagline: "An anti-hate satire.", rating: "⭐ 7.9" },
    { title: "Paddington 2", year: "2017", tagline: "It takes a bear to catch a thief.", rating: "⭐ 7.8" },
    { title: "Airplane!", year: "1980", tagline: "Thank God it's only a motion picture!", rating: "⭐ 7.7" },
    { title: "Dr. Strangelove", year: "1964", tagline: "How I Learned to Stop Worrying and Love the Bomb.", rating: "⭐ 8.4" },
    { title: "The Hangover", year: "2009", tagline: "Some guys just can't handle Vegas.", rating: "⭐ 7.7" },
    { title: "Anchorman: The Legend of Ron Burgundy", year: "2004", tagline: "His voice is the soundtrack of a nation.", rating: "⭐ 7.2" },
    { title: "Napoleon Dynamite", year: "2004", tagline: "He's out to prove he's got nothing to prove.", rating: "⭐ 6.9" },
    { title: "Booksmart", year: "2019", tagline: "Getting straight A's. Giving zero F's.", rating: "⭐ 7.1" },
    { title: "Bridesmaids", year: "2011", tagline: "Chick flicks don't have to suck.", rating: "⭐ 6.8" },
    { title: "Elf", year: "2003", tagline: "This holiday, discover your inner elf.", rating: "⭐ 7.1" }
  ],
  'Thriller': [
    { title: "Parasite", year: "2019", tagline: "Act like you own the place.", rating: "⭐ 8.5" },
    { title: "Se7en", year: "1995", tagline: "Seven deadly sins. Seven ways to die.", rating: "⭐ 8.6" },
    { title: "Gone Girl", year: "2014", tagline: "You don't know what you've got 'til it's...", rating: "⭐ 8.1" },
    { title: "Prisoners", year: "2013", tagline: "Every moment matters.", rating: "⭐ 8.1" },
    { title: "Shutter Island", year: "2010", tagline: "Someone is missing.", rating: "⭐ 8.2" },
    { title: "Nightcrawler", year: "2014", tagline: "The city shines brightest at night.", rating: "⭐ 7.8" },
    { title: "Uncut Gems", year: "2019", tagline: "This is how I win.", rating: "⭐ 7.4" },
    { title: "The Silence of the Lambs", year: "1991", tagline: "To enter the mind of a killer she must challenge the mind of a madman.", rating: "⭐ 8.6" },
    { title: "Zodiac", year: "2007", tagline: "There's more than one way to lose your life to a killer.", rating: "⭐ 7.7" },
    { title: "Oldboy", year: "2003", tagline: "15 years of imprisonment, 5 days of vengeance.", rating: "⭐ 8.3" },
    { title: "Memento", year: "2000", tagline: "Some memories are best forgotten.", rating: "⭐ 8.4" },
    { title: "The Prestige", year: "2006", tagline: "Are you watching closely?", rating: "⭐ 8.5" },
    { title: "Black Swan", year: "2010", tagline: "I just want to be perfect.", rating: "⭐ 8.0" },
    { title: "No Country for Old Men", year: "2007", tagline: "There are no clean getaways.", rating: "⭐ 8.2" },
    { title: "Sicario", year: "2015", tagline: "The border is just another line to cross.", rating: "⭐ 7.7" },
    { title: "Drive", year: "2011", tagline: "There are no clean getaways.", rating: "⭐ 7.8" },
    { title: "Arrival", year: "2016", tagline: "Why are they here?", rating: "⭐ 7.9" },
    { title: "Ex Machina", year: "2014", tagline: "To erase the line between man and machine.", rating: "⭐ 7.7" },
    { title: "Get Out", year: "2017", tagline: "Just because you're invited, doesn't mean you're welcome.", rating: "⭐ 7.8" },
    { title: "10 Cloverfield Lane", year: "2016", tagline: "Monsters come in many forms.", rating: "⭐ 7.2" },
    { title: "The Departed", year: "2006", tagline: "Lies. Betrayal. Sacrifice.", rating: "⭐ 8.5" },
    { title: "Fight Club", year: "1999", tagline: "Mischief. Mayhem. Soap.", rating: "⭐ 8.8" },
    { title: "Joker", year: "2019", tagline: "Put on a happy face.", rating: "⭐ 8.4" },
    { title: "Taxi Driver", year: "1976", tagline: "On every street in every city, there's a nobody who dreams of being a somebody.", rating: "⭐ 8.2" },
    { title: "The Usual Suspects", year: "1995", tagline: "The greatest trick the Devil ever pulled was convincing the world he didn't exist.", rating: "⭐ 8.5" },
    { title: "Rear Window", year: "1954", tagline: "It only takes one witness to spoil the perfect crime.", rating: "⭐ 8.5" },
    { title: "Vertigo", year: "1958", tagline: "A Hitchcock masterpiece.", rating: "⭐ 8.3" },
    { title: "Chinatown", year: "1974", tagline: "You're with me, Jake.", rating: "⭐ 8.2" },
    { title: "Blue Velvet", year: "1986", tagline: "It's a strange world.", rating: "⭐ 7.7" },
    { title: "Mulholland Drive", year: "2001", tagline: "A love story in the city of dreams.", rating: "⭐ 7.9" },
    { title: "Searching", year: "2018", tagline: "No one is lost without a trace.", rating: "⭐ 7.6" },
    { title: "Source Code", year: "2011", tagline: "Make every second count.", rating: "⭐ 7.5" },
    { title: "Collateral", year: "2004", tagline: "It started like any other night.", rating: "⭐ 7.5" }
  ],
  'Romance': [
    { title: "La La Land", year: "2016", tagline: "Here's to the fools who dream.", rating: "⭐ 8.0" },
    { title: "Before Sunrise", year: "1995", tagline: "Can the greatest romance of your life last only one night?", rating: "⭐ 8.1" },
    { title: "About Time", year: "2013", tagline: "What if every moment in life came with a second chance?", rating: "⭐ 7.8" },
    { title: "Portrait of a Lady on Fire", year: "2019", tagline: "Do not regret. Remember.", rating: "⭐ 8.1" },
    { title: "500 Days of Summer", year: "2009", tagline: "This is not a love story.", rating: "⭐ 7.7" },
    { title: "Eternal Sunshine of the Spotless Mind", year: "2004", tagline: "You can erase someone from your mind.", rating: "⭐ 8.3" },
    { title: "The Notebook", year: "2004", tagline: "Behind every great love is a great story.", rating: "⭐ 7.8" },
    { title: "Her", year: "2013", tagline: "A Spike Jonze Love Story.", rating: "⭐ 8.0" },
    { title: "Call Me by Your Name", year: "2017", tagline: "Is it better to speak or die?", rating: "⭐ 7.8" },
    { title: "Past Lives", year: "2023", tagline: "Destiny is a matter of choice.", rating: "⭐ 7.9" },
    { title: "Amélie", year: "2001", tagline: "She'll change your life.", rating: "⭐ 8.3" },
    { title: "Pride & Prejudice", year: "2005", tagline: "Sometimes the last person on earth you want to be with is the one person you can't be without.", rating: "⭐ 7.8" },
    { title: "10 Things I Hate About You", year: "1999", tagline: "How do I loathe thee? Let me count the ways.", rating: "⭐ 7.3" },
    { title: "Crazy Rich Asians", year: "2018", tagline: "The only thing crazier than love is family.", rating: "⭐ 6.9" },
    { title: "The Princess Bride", year: "1987", tagline: "As you wish.", rating: "⭐ 8.0" },
    { title: "Moonlight", year: "2016", tagline: "This is the story of a lifetime.", rating: "⭐ 7.4" },
    { title: "Silver Linings Playbook", year: "2012", tagline: "Watch for the signs.", rating: "⭐ 7.7" },
    { title: "Punch-Drunk Love", year: "2002", tagline: "He needed a push.", rating: "⭐ 7.3" },
    { title: "Scott Pilgrim vs. the World", year: "2010", tagline: "An epic of epic epicness.", rating: "⭐ 7.5" },
    { title: "When Harry Met Sally...", year: "1989", tagline: "Can men and women ever just be friends?", rating: "⭐ 7.7" },
    { title: "Your Name", year: "2016", tagline: "I am looking for you, who I have never met.", rating: "⭐ 8.4" },
    { title: "Titanic", year: "1997", tagline: "Nothing on Earth could come between them.", rating: "⭐ 7.9" },
    { title: "Casablanca", year: "1942", tagline: "Here's looking at you, kid.", rating: "⭐ 8.5" },
    { title: "Before Sunset", year: "2004", tagline: "Nine years later...", rating: "⭐ 8.1" },
    { title: "Love Actually", year: "2003", tagline: "The ultimate romantic comedy.", rating: "⭐ 7.6" },
    { title: "Before Midnight", year: "2013", tagline: "The greatest romance of a generation.", rating: "⭐ 7.9" },
    { title: "Roman Holiday", year: "1953", tagline: "Romance in the eternal city.", rating: "⭐ 8.0" },
    { title: "Brokeback Mountain", year: "2005", tagline: "Love is a force of nature.", rating: "⭐ 7.7" },
    { title: "Carol", year: "2015", tagline: "Some people change your life forever.", rating: "⭐ 7.2" },
    { title: "Notting Hill", year: "1999", tagline: "Can the most famous film star in the world fall for just an ordinary guy?", rating: "⭐ 7.2" },
    { title: "The Big Sick", year: "2017", tagline: "An awkward true story.", rating: "⭐ 7.5" },
    { title: "Singin' in the Rain", year: "1952", tagline: "What a glorious feeling!", rating: "⭐ 8.3" },
    { title: "In the Mood for Love", year: "2000", tagline: "Feel the heat, keep the feeling burning, let the sensation explode.", rating: "⭐ 8.1" }
  ],
  'Anime': [
    { title: "Spirited Away", year: "2001", tagline: "Don't look back.", rating: "⭐ 8.6" },
    { title: "Your Name", year: "2016", tagline: "I am looking for you, who I have never met.", rating: "⭐ 8.4" },
    { title: "Akira", year: "1988", tagline: "Neo-Tokyo is about to explode.", rating: "⭐ 8.0" },
    { title: "Princess Mononoke", year: "1997", tagline: "The fate of the world rests on the courage of one warrior.", rating: "⭐ 8.3" },
    { title: "Perfect Blue", year: "1997", tagline: "The color of illusion is perfect blue.", rating: "⭐ 8.0" },
    { title: "A Silent Voice", year: "2016", tagline: "The hardest thing to do is forgive yourself.", rating: "⭐ 8.1" },
    { title: "Howl's Moving Castle", year: "2004", tagline: "The two lived there.", rating: "⭐ 8.2" },
    { title: "Grave of the Fireflies", year: "1988", tagline: "4 September 1945. That was the night I died.", rating: "⭐ 8.5" },
    { title: "Neon Genesis Evangelion: The End of Evangelion", year: "1997", tagline: "The fate of destruction is also the joy of rebirth.", rating: "⭐ 8.0" },
    { title: "Ghost in the Shell", year: "1995", tagline: "It found a voice... Now it needs a body.", rating: "⭐ 7.9" },
    { title: "Paprika", year: "2006", tagline: "This is your brain on anime.", rating: "⭐ 7.7" },
    { title: "My Neighbor Totoro", year: "1988", tagline: "Come play with us.", rating: "⭐ 8.1" },
    { title: "Weathering with You", year: "2019", tagline: "This is the story of the world's secret.", rating: "⭐ 7.5" },
    { title: "Suzume", year: "2022", tagline: "I'll find you.", rating: "⭐ 7.7" },
    { title: "The Boy and the Heron", year: "2023", tagline: "Where death comes to an end, life finds a new beginning.", rating: "⭐ 7.6" },
    { title: "Redline", year: "2009", tagline: "Racing has never been this dangerous.", rating: "⭐ 7.5" },
    { title: "Tokyo Godfathers", year: "2003", tagline: "Meet the ultimate odd couple... trio.", rating: "⭐ 7.8" },
    { title: "Summer Wars", year: "2009", tagline: "Connection is the key.", rating: "⭐ 7.4" },
    { title: "The Girl Who Leapt Through Time", year: "2006", tagline: "Waiting for you in the future.", rating: "⭐ 7.7" },
    { title: "Wolf Children", year: "2012", tagline: "A mother's love makes anything possible.", rating: "⭐ 8.1" },
    { title: "Ninja Scroll", year: "1993", tagline: "Black magic, deadly martial arts and a love stronger than death.", rating: "⭐ 7.8" },
    { title: "Cowboy Bebop: The Movie", year: "2001", tagline: "They're just a couple of cowboys.", rating: "⭐ 7.9" },
    { title: "Promare", year: "2019", tagline: "Burn it all down.", rating: "⭐ 7.0" },
    { title: "Demon Slayer: Mugen Train", year: "2020", tagline: "Set your heart ablaze.", rating: "⭐ 8.2" },
    { title: "Jujutsu Kaisen 0", year: "2021", tagline: "Love is the most twisted curse of all.", rating: "⭐ 7.8" },
    { title: "Nausicaä of the Valley of the Wind", year: "1984", tagline: "A young princess fights to save her world.", rating: "⭐ 8.0" },
    { title: "Castle in the Sky", year: "1986", tagline: "One day you'll be a legend.", rating: "⭐ 8.0" },
    { title: "Kiki's Delivery Service", year: "1989", tagline: "I was feeling a little blue, but I'm better now.", rating: "⭐ 7.8" },
    { title: "Porco Rosso", year: "1992", tagline: "A pig's gotta fly.", rating: "⭐ 7.7" },
    { title: "The Wind Rises", year: "2013", tagline: "We must live.", rating: "⭐ 7.7" },
    { title: "5 Centimeters Per Second", year: "2007", tagline: "A chain of short stories about their distance.", rating: "⭐ 7.5" },
    { title: "I Want to Eat Your Pancreas", year: "2018", tagline: "The secret I didn't tell anyone.", rating: "⭐ 8.0" }
  ],
  'Drama': [
    { title: "The Shawshank Redemption", year: "1994", tagline: "Fear can hold you prisoner. Hope can set you free.", rating: "⭐ 9.3" },
    { title: "Fight Club", year: "1999", tagline: "Mischief. Mayhem. Soap.", rating: "⭐ 8.8" },
    { title: "Good Will Hunting", year: "1997", tagline: "Some people can't believe in themselves.", rating: "⭐ 8.3" },
    { title: "Whiplash", year: "2014", tagline: "There are no two words more harmful than 'good job'.", rating: "⭐ 8.5" },
    { title: "The Social Network", year: "2010", tagline: "You don't get to 500 million friends without making a few enemies.", rating: "⭐ 7.8" },
    { title: "The Godfather", year: "1972", tagline: "An offer you can't refuse.", rating: "⭐ 9.2" },
    { title: "Pulp Fiction", year: "1994", tagline: "Just because you are a character doesn't mean that you have character.", rating: "⭐ 8.9" },
    { title: "Forrest Gump", year: "1994", tagline: "Life is like a box of chocolates.", rating: "⭐ 8.8" },
    { title: "Schindler's List", year: "1993", tagline: "Whoever saves one life, saves the world entire.", rating: "⭐ 9.0" },
    { title: "12 Angry Men", year: "1957", tagline: "Life is in their hands. Death is on their minds.", rating: "⭐ 9.0" },
    { title: "Parasite", year: "2019", tagline: "Act like you own the place.", rating: "⭐ 8.5" },
    { title: "Joker", year: "2019", tagline: "Put on a happy face.", rating: "⭐ 8.4" },
    { title: "The Truman Show", year: "1998", tagline: "On the air. Unaware.", rating: "⭐ 8.2" },
    { title: "Dead Poets Society", year: "1989", tagline: "Carpe Diem. Seize the day.", rating: "⭐ 8.1" },
    { title: "Spotlight", year: "2015", tagline: "Break the story. Break the silence.", rating: "⭐ 8.1" },
    { title: "A Beautiful Mind", year: "2001", tagline: "He saw the world in a way no one could have imagined.", rating: "⭐ 8.2" },
    { title: "Into the Wild", year: "2007", tagline: "Happiness only real when shared.", rating: "⭐ 8.1" },
    { title: "The Green Mile", year: "1999", tagline: "Miracles happen in the most unexpected places.", rating: "⭐ 8.6" },
    { title: "American Beauty", year: "1999", tagline: "Look closer.", rating: "⭐ 8.3" },
    { title: "Requiem for a Dream", year: "2000", tagline: "The American dream... is a nightmare.", rating: "⭐ 8.3" },
    { title: "There Will Be Blood", year: "2007", tagline: "There will be greed. There will be vengeance.", rating: "⭐ 8.2" },
    { title: "No Country for Old Men", year: "2007", tagline: "There are no clean getaways.", rating: "⭐ 8.2" },
    { title: "The Wolf of Wall Street", year: "2013", tagline: "Earn. Spend. Party.", rating: "⭐ 8.2" },
    { title: "Marriage Story", year: "2019", tagline: "Where there is a love, there is a way.", rating: "⭐ 7.9" },
    { title: "La Haine", year: "1995", tagline: "So far, so good.", rating: "⭐ 8.1" },
    { title: "Citizen Kane", year: "1941", tagline: "It's terrific!", rating: "⭐ 8.3" },
    { title: "One Flew Over the Cuckoo's Nest", year: "1975", tagline: "If he's crazy, what does that make you?", rating: "⭐ 8.7" },
    { title: "City of God", year: "2002", tagline: "If you run, the beast catches you; if you stay, the beast eats you.", rating: "⭐ 8.6" },
    { title: "Saving Private Ryan", year: "1998", tagline: "The mission is a man.", rating: "⭐ 8.6" },
    { title: "The Pianist", year: "2002", tagline: "Music was his passion. Survival was his masterpiece.", rating: "⭐ 8.5" },
    { title: "American History X", year: "1998", tagline: "See it with your eyes wide open.", rating: "⭐ 8.5" },
    { title: "Gladiator", year: "2000", tagline: "A hero will rise.", rating: "⭐ 8.5" }
  ],
  'Mystery': [
    { title: "Knives Out", year: "2019", tagline: "Hell, I suspect everyone.", rating: "⭐ 7.9" },
    { title: "Se7en", year: "1995", tagline: "Long is the way and hard, that out of Hell leads up to Light.", rating: "⭐ 8.6" },
    { title: "Shutter Island", year: "2010", tagline: "Someone is missing.", rating: "⭐ 8.2" },
    { title: "Memento", year: "2000", tagline: "Some memories are best forgotten.", rating: "⭐ 8.4" },
    { title: "Gone Girl", year: "2014", tagline: "You don't know what you've got 'til it's...", rating: "⭐ 8.1" },
    { title: "Prisoners", year: "2013", tagline: "Every moment matters.", rating: "⭐ 8.1" },
    { title: "The Prestige", year: "2006", tagline: "Are you watching closely?", rating: "⭐ 8.5" },
    { title: "Zodiac", year: "2007", tagline: "There's more than one way to lose your life to a killer.", rating: "⭐ 7.7" },
    { title: "The Girl with the Dragon Tattoo", year: "2011", tagline: "Evil shall be expelled.", rating: "⭐ 7.8" },
    { title: "Arrival", year: "2016", tagline: "Why are they here?", rating: "⭐ 7.9" },
    { title: "Mulholland Drive", year: "2001", tagline: "A love story in the city of dreams.", rating: "⭐ 7.9" },
    { title: "Oldboy", year: "2003", tagline: "Laugh and the world laughs with you. Weep and you weep alone.", rating: "⭐ 8.4" },
    { title: "Blade Runner 2049", year: "2017", tagline: "More human than human.", rating: "⭐ 8.0" },
    { title: "Glass Onion", year: "2022", tagline: "A Knives Out Mystery.", rating: "⭐ 7.1" },
    { title: "Rear Window", year: "1954", tagline: "It only takes one witness to spoil the perfect crime.", rating: "⭐ 8.5" },
    { title: "Vertigo", year: "1958", tagline: "A Hitchcock masterpiece.", rating: "⭐ 8.3" },
    { title: "Chinatown", year: "1974", tagline: "You're with me, Jake.", rating: "⭐ 8.2" },
    { title: "L.A. Confidential", year: "1997", tagline: "Off the record, on the QT, and very hush-hush.", rating: "⭐ 8.2" },
    { title: "Mystic River", year: "2003", tagline: "We bury our sins here, Dave. We wash them clean.", rating: "⭐ 7.9" },
    { title: "Sherlock Holmes", year: "2009", tagline: "Nothing escapes him.", rating: "⭐ 7.6" },
    { title: "Identity", year: "2003", tagline: "The secret lies within.", rating: "⭐ 7.3" },
    { title: "The Sixth Sense", year: "1999", tagline: "I see dead people.", rating: "⭐ 8.2" },
    { title: "Gone Baby Gone", year: "2007", tagline: "Everyone wants the truth... until they find it.", rating: "⭐ 7.6" },
    { title: "Source Code", year: "2011", tagline: "Make every second count.", rating: "⭐ 7.5" },
    { title: "Blue Velvet", year: "1986", tagline: "It's a strange world.", rating: "⭐ 7.7" },
    { title: "Burning", year: "2018", tagline: "Now tell the truth.", rating: "⭐ 7.5" },
    { title: "Wind River", year: "2017", tagline: "Nothing is harder to track than the truth.", rating: "⭐ 7.7" },
    { title: "Memories of Murder", year: "2003", tagline: "The worst of them will never be caught.", rating: "⭐ 8.1" },
    { title: "Searching", year: "2018", tagline: "No one is lost without a trace.", rating: "⭐ 7.6" },
    { title: "The Hateful Eight", year: "2015", tagline: "No one comes up here without a damn good reason.", rating: "⭐ 7.8" }
  ],
  'Fantasy': [
    { title: "The Lord of the Rings: The Fellowship of the Ring", year: "2001", tagline: "One Ring to Rule Them All.", rating: "⭐ 8.8" },
    { title: "Harry Potter and the Prisoner of Azkaban", year: "2004", tagline: "Something wicked this way comes.", rating: "⭐ 7.9" },
    { title: "Pan's Labyrinth", year: "2006", tagline: "Innocence has a power evil cannot imagine.", rating: "⭐ 8.2" },
    { title: "Spirited Away", year: "2001", tagline: "Don't look back.", rating: "⭐ 8.6" },
    { title: "The Princess Bride", year: "1987", tagline: "She is the only thing that stands between them and the darkness.", rating: "⭐ 8.0" },
    { title: "Howl's Moving Castle", year: "2004", tagline: "The two lived there.", rating: "⭐ 8.2" },
    { title: "Stardust", year: "2007", tagline: "This summer a star falls. The chase begins.", rating: "⭐ 7.6" },
    { title: "Pirates of the Caribbean: The Curse of the Black Pearl", year: "2003", tagline: "Prepare to be blown out of the water.", rating: "⭐ 8.1" },
    { title: "Big Fish", year: "2003", tagline: "An adventure as big as life itself.", rating: "⭐ 8.0" },
    { title: "The Green Knight", year: "2021", tagline: "One year hence.", rating: "⭐ 6.6" },
    { title: "The Wizard of Oz", year: "1939", tagline: "There's no place like home.", rating: "⭐ 8.1" },
    { title: "Labyrinth", year: "1986", tagline: "Where everything seems possible and nothing is what it seems.", rating: "⭐ 7.3" },
    { title: "Fantastic Mr. Fox", year: "2009", tagline: "Dig the life fantastic.", rating: "⭐ 7.9" },
    { title: "Coraline", year: "2009", tagline: "Be careful what you wish for.", rating: "⭐ 7.7" },
    { title: "Groundhog Day", year: "1993", tagline: "He's having the day of his life... over and over again.", rating: "⭐ 8.0" },
    { title: "The Lord of the Rings: The Two Towers", year: "2002", tagline: "A New Power Is Rising.", rating: "⭐ 8.8" },
    { title: "The Lord of the Rings: The Return of the King", year: "2003", tagline: "There can be no triumph without loss.", rating: "⭐ 9.0" },
    { title: "Harry Potter and the Sorcerer's Stone", year: "2001", tagline: "Let the magic begin.", rating: "⭐ 7.6" },
    { title: "Harry Potter and the Deathly Hallows: Part 2", year: "2011", tagline: "It all ends.", rating: "⭐ 8.1" },
    { title: "The Shape of Water", year: "2017", tagline: "A Fairy Tale for Troubled Times.", rating: "⭐ 7.3" },
    { title: "Life of Pi", year: "2012", tagline: "Believe the unbelievable.", rating: "⭐ 7.9" },
    { title: "Edward Scissorhands", year: "1990", tagline: "His story will touch you, even though he can't.", rating: "⭐ 7.9" },
    { title: "Mary Poppins", year: "1964", tagline: "It's supercalifragilisticexpialidocious!", rating: "⭐ 7.8" },
    { title: "Beetlejuice", year: "1988", tagline: "He's guaranteed to put some life in your afterlife.", rating: "⭐ 7.5" },
    { title: "Willy Wonka & the Chocolate Factory", year: "1971", tagline: "It's Scrumdiddlyumptious!", rating: "⭐ 7.8" },
    { title: "The NeverEnding Story", year: "1984", tagline: "A boy who needs a friend finds a world that needs a hero.", rating: "⭐ 7.3" },
    { title: "Enchanted", year: "2007", tagline: "The fairytale is about to get real.", rating: "⭐ 7.1" },
    { title: "Midnight in Paris", year: "2011", tagline: "Unlocking the mystery of the city of lights.", rating: "⭐ 7.7" },
    { title: "Paddington 2", year: "2017", tagline: "It takes a bear to catch a thief.", rating: "⭐ 7.8" },
    { title: "Crouching Tiger, Hidden Dragon", year: "2000", tagline: "A timeless story of strength, secrets and two warriors.", rating: "⭐ 7.9" }
  ],
  'Crime': [
    { title: "The Godfather", year: "1972", tagline: "An offer you can't refuse.", rating: "⭐ 9.2" },
    { title: "The Godfather Part II", year: "1974", tagline: "I don't feel I have to wipe everybody out, Tom. Just my enemies.", rating: "⭐ 9.0" },
    { title: "Pulp Fiction", year: "1994", tagline: "Just because you are a character doesn't mean that you have character.", rating: "⭐ 8.9" },
    { title: "Goodfellas", year: "1990", tagline: "As far back as I can remember, I always wanted to be a gangster.", rating: "⭐ 8.7" },
    { title: "City of God", year: "2002", tagline: "If you run, the beast catches you; if you stay, the beast eats you.", rating: "⭐ 8.6" },
    { title: "Se7en", year: "1995", tagline: "Seven deadly sins. Seven ways to die.", rating: "⭐ 8.6" },
    { title: "The Silence of the Lambs", year: "1991", tagline: "To enter the mind of a killer she must challenge the mind of a madman.", rating: "⭐ 8.6" },
    { title: "The Usual Suspects", year: "1995", tagline: "The greatest trick the Devil ever pulled was convincing the world he didn't exist.", rating: "⭐ 8.5" },
    { title: "Léon: The Professional", year: "1994", tagline: "If you want the job done right, hire a professional.", rating: "⭐ 8.5" },
    { title: "The Departed", year: "2006", tagline: "Lies. Betrayal. Sacrifice.", rating: "⭐ 8.5" },
    { title: "Reservoir Dogs", year: "1992", tagline: "Every dog has his day.", rating: "⭐ 8.3" },
    { title: "Heat", year: "1995", tagline: "A Los Angeles crime saga.", rating: "⭐ 8.3" },
    { title: "L.A. Confidential", year: "1997", tagline: "Everything is suspect... everyone is for sale... and nothing is what it seems.", rating: "⭐ 8.2" },
    { title: "Scarface", year: "1983", tagline: "The world is yours.", rating: "⭐ 8.3" },
    { title: "Casino", year: "1995", tagline: "No one stays at the top forever.", rating: "⭐ 8.2" },
    { title: "Fargo", year: "1996", tagline: "A lot can happen in the middle of nowhere.", rating: "⭐ 8.1" },
    { title: "Prisoners", year: "2013", tagline: "Every moment matters.", rating: "⭐ 8.1" },
    { title: "No Country for Old Men", year: "2007", tagline: "There are no clean getaways.", rating: "⭐ 8.2" },
    { title: "Zodiac", year: "2007", tagline: "There's more than one way to lose your life to a killer.", rating: "⭐ 7.7" },
    { title: "American History X", year: "1998", tagline: "See it with your eyes wide open.", rating: "⭐ 8.5" },
    { title: "The Green Mile", year: "1999", tagline: "Miracles happen in the most unexpected places.", rating: "⭐ 8.6" },
    { title: "Catch Me If You Can", year: "2002", tagline: "The true story of a real fake.", rating: "⭐ 8.1" },
    { title: "American Gangster", year: "2007", tagline: "There are two sides to the American dream.", rating: "⭐ 7.8" },
    { title: "The Untouchables", year: "1987", tagline: "Never stop fighting till the fight is done.", rating: "⭐ 7.8" },
    { title: "Lock, Stock and Two Smoking Barrels", year: "1998", tagline: "A disgraced math wiz. A pimp. A drug dealer.", rating: "⭐ 8.1" },
    { title: "Snatch", year: "2000", tagline: "Stealin' stones and breakin' bones.", rating: "⭐ 8.2" },
    { title: "Training Day", year: "2001", tagline: "The only thing more dangerous than the line being crossed, is the cop who will cross it.", rating: "⭐ 7.7" },
    { title: "Drive", year: "2011", tagline: "There are no clean getaways.", rating: "⭐ 7.8" },
    { title: "Sicario", year: "2015", tagline: "The border is just another line to cross.", rating: "⭐ 7.6" },
    { title: "The Irishman", year: "2019", tagline: "I heard you paint houses.", rating: "⭐ 7.8" },
    { title: "Joker", year: "2019", tagline: "Put on a happy face.", rating: "⭐ 8.4" },
    { title: "Nightcrawler", year: "2014", tagline: "The city shines brightest at night.", rating: "⭐ 7.8" },
    { title: "Memories of Murder", year: "2003", tagline: "The worst of them will never be caught.", rating: "⭐ 8.1" },
    { title: "Oldboy", year: "2003", tagline: "Laugh and the world laughs with you. Weep and you weep alone.", rating: "⭐ 8.3" },
    { title: "Ocean's Eleven", year: "2001", tagline: "Are you in or out?", rating: "⭐ 7.7" },
    { title: "Dog Day Afternoon", year: "1975", tagline: "The bank robbery was supposed to last ten minutes.", rating: "⭐ 8.0" },
    { title: "Taxi Driver", year: "1976", tagline: "On every street in every city, there's a nobody who dreams of being a somebody.", rating: "⭐ 8.2" },
    { title: "Once Upon a Time in America", year: "1984", tagline: "As boys, they made a pact to share their fortunes, their loves, their lives.", rating: "⭐ 8.3" }
  ]
};

// --- TV SHOWS DATABASE ---
export const SHOW_DB: Record<Genre, MovieOption[]> = {
  'Action': [
    { title: "The Boys", year: "2019-", tagline: "Never meet your heroes.", rating: "⭐ 8.7" },
    { title: "Daredevil", year: "2015-2018", tagline: "Justice is blind.", rating: "⭐ 8.6" },
    { title: "Reacher", year: "2022-", tagline: "Details matter.", rating: "⭐ 8.1" },
    { title: "Band of Brothers", year: "2001", tagline: "They depended on each other. And the world depended on them.", rating: "⭐ 9.4" },
    { title: "The Mandalorian", year: "2019-", tagline: "This is the way.", rating: "⭐ 8.7" },
    { title: "Peacemaker", year: "2022-", tagline: "Give peace a chance.", rating: "⭐ 8.3" },
    { title: "Vikings", year: "2013-2020", tagline: "The storm is coming.", rating: "⭐ 8.5" },
    { title: "Warrior", year: "2019-", tagline: "Fight for your family. Fight for your life.", rating: "⭐ 8.4" },
    { title: "The Punisher", year: "2017-2019", tagline: "The truth must be taken.", rating: "⭐ 8.5" },
    { title: "Jack Ryan", year: "2018-2023", tagline: "Whatever the risk.", rating: "⭐ 8.0" },
    { title: "Into the Badlands", year: "2015-2019", tagline: "There is no god in the badlands.", rating: "⭐ 7.9" },
    { title: "Banshee", year: "2013-2016", tagline: "Small town. Big secrets.", rating: "⭐ 8.4" },
    { title: "Spartacus", year: "2010-2013", tagline: "Blood and sand.", rating: "⭐ 8.5" },
    { title: "24", year: "2001-2010", tagline: "The clock is ticking.", rating: "⭐ 8.4" },
    { title: "Prison Break", year: "2005-2017", tagline: "Break out.", rating: "⭐ 8.3" },
    { title: "Arrow", year: "2012-2020", tagline: "Destiny leaves its mark.", rating: "⭐ 7.5" },
    { title: "Cobra Kai", year: "2018-", tagline: "Strike first. Strike hard. No mercy.", rating: "⭐ 8.5" },
    { title: "Alice in Borderland", year: "2020-", tagline: "Play the game or die.", rating: "⭐ 7.7" },
    { title: "Kingdom", year: "2019-", tagline: "Blood will spill.", rating: "⭐ 8.3" },
    { title: "Blue Eye Samurai", year: "2023-", tagline: "Revenge is a dish best served cold.", rating: "⭐ 8.8" },
    { title: "Shogun", year: "2024", tagline: "The future is forged by the past.", rating: "⭐ 8.8" },
    { title: "Fallout", year: "2024", tagline: "The end was just the beginning.", rating: "⭐ 8.5" },
    { title: "Gen V", year: "2023-", tagline: "School is in session.", rating: "⭐ 7.8" },
    { title: "Invincible", year: "2021-", tagline: "It's about time.", rating: "⭐ 8.7" },
    { title: "One Piece (Live Action)", year: "2023-", tagline: "The pirates are coming.", rating: "⭐ 8.3" },
    { title: "Squid Game", year: "2021-", tagline: "45.6 Billion Won is child's play.", rating: "⭐ 8.0" },
    { title: "Money Heist", year: "2017-2021", tagline: "The perfect robbery.", rating: "⭐ 8.2" },
    { title: "Burn Notice", year: "2007-2013", tagline: "Spies don't get fired.", rating: "⭐ 8.0" },
    { title: "Person of Interest", year: "2011-2016", tagline: "You are being watched.", rating: "⭐ 8.5" },
    { title: "Justified", year: "2010-2015", tagline: "Lawman.", rating: "⭐ 8.6" },
    { title: "The Last Kingdom", year: "2015-2022", tagline: "Destiny is all.", rating: "⭐ 8.5" }
  ],
  'Sci-Fi': [
    { title: "Black Mirror", year: "2011-", tagline: "The future is bright.", rating: "⭐ 8.7" },
    { title: "Severance", year: "2022-", tagline: "We're all family here.", rating: "⭐ 8.7" },
    { title: "Stranger Things", year: "2016-", tagline: "One summer can change everything.", rating: "⭐ 8.7" },
    { title: "The Expanse", year: "2015-2022", tagline: "We are gone.", rating: "⭐ 8.5" },
    { title: "Westworld", year: "2016-2022", tagline: "Chaos takes control.", rating: "⭐ 8.5" },
    { title: "Dark", year: "2017-2020", tagline: "The question is not where, but when.", rating: "⭐ 8.7" },
    { title: "Firefly", year: "2002", tagline: "You can't take the sky from me.", rating: "⭐ 9.0" },
    { title: "Battlestar Galactica", year: "2004-2009", tagline: "The cylons were created by man.", rating: "⭐ 8.7" },
    { title: "Andor", year: "2022-", tagline: "The rebellion begins.", rating: "⭐ 8.4" },
    { title: "Silo", year: "2023-", tagline: "The truth will surface.", rating: "⭐ 8.1" },
    { title: "Foundation", year: "2021-", tagline: "Change your fate.", rating: "⭐ 7.6" },
    { title: "Love, Death & Robots", year: "2019-", tagline: "NSFW.", rating: "⭐ 8.4" },
    { title: "Doctor Who", year: "2005-", tagline: "It's bigger on the inside.", rating: "⭐ 8.6" },
    { title: "Orphan Black", year: "2013-2017", tagline: "One. Of. A. Kind.", rating: "⭐ 8.3" },
    { title: "Fringe", year: "2008-2013", tagline: "Impossible is just a word.", rating: "⭐ 8.4" },
    { title: "Lost", year: "2004-2010", tagline: "Everything happens for a reason.", rating: "⭐ 8.3" },
    { title: "Sense8", year: "2015-2018", tagline: "I am also a we.", rating: "⭐ 8.2" },
    { title: "Altered Carbon", year: "2018-2020", tagline: "No body lives forever.", rating: "⭐ 7.9" },
    { title: "Devs", year: "2020", tagline: "Nothing happens for a reason.", rating: "⭐ 7.7" },
    { title: "Station Eleven", year: "2021", tagline: "Survival is insufficient.", rating: "⭐ 7.6" },
    { title: "Star Trek: The Next Generation", year: "1987-1994", tagline: "To boldly go.", rating: "⭐ 8.7" },
    { title: "Star Trek: Deep Space Nine", year: "1993-1999", tagline: "The adventure continues.", rating: "⭐ 8.1" },
    { title: "The X-Files", year: "1993-2018", tagline: "The truth is out there.", rating: "⭐ 8.6" },
    { title: "Rick and Morty", year: "2013-", tagline: "Wubba Lubba Dub Dub!", rating: "⭐ 9.1" },
    { title: "Futurama", year: "1999-2023", tagline: "The future is here.", rating: "⭐ 8.5" },
    { title: "Counterpart", year: "2017-2019", tagline: "What if you could meet your other self?", rating: "⭐ 8.0" },
    { title: "For All Mankind", year: "2019-", tagline: "The race continues.", rating: "⭐ 8.1" },
    { title: "Bodies", year: "2023", tagline: "Four detectives. Four timelines. One body.", rating: "⭐ 7.3" },
    { title: "3 Body Problem", year: "2024-", tagline: "We are not alone.", rating: "⭐ 7.6" },
    { title: "12 Monkeys", year: "2015-2018", tagline: "Undo history.", rating: "⭐ 7.7" }
  ],
  'Horror': [
    { title: "The Haunting of Hill House", year: "2018", tagline: "Come home.", rating: "⭐ 8.6" },
    { title: "Stranger Things", year: "2016-", tagline: "Upside Down.", rating: "⭐ 8.7" },
    { title: "Hannibal", year: "2013-2015", tagline: "Eat the rude.", rating: "⭐ 8.5" },
    { title: "Midnight Mass", year: "2021", tagline: "Be not afraid.", rating: "⭐ 7.7" },
    { title: "The Last of Us", year: "2023-", tagline: "When you're lost in the darkness, look for the light.", rating: "⭐ 8.7" },
    { title: "American Horror Story", year: "2011-", tagline: "Get ready to be scared.", rating: "⭐ 8.0" },
    { title: "Penny Dreadful", year: "2014-2016", tagline: "There is some thing within us all.", rating: "⭐ 8.2" },
    { title: "Ash vs Evil Dead", year: "2015-2018", tagline: "Groovy.", rating: "⭐ 8.4" },
    { title: "The Walking Dead", year: "2010-2022", tagline: "Fight the dead. Fear the living.", rating: "⭐ 8.1" },
    { title: "What We Do in the Shadows", year: "2019-", tagline: "Vampires in Staten Island.", rating: "⭐ 8.6" },
    { title: "Bates Motel", year: "2013-2017", tagline: "A boy's best friend is his mother.", rating: "⭐ 8.1" },
    { title: "Marianne", year: "2019", tagline: "Don't watch alone.", rating: "⭐ 7.4" },
    { title: "Channel Zero", year: "2016-2018", tagline: "Nightmares come from the internet.", rating: "⭐ 7.1" },
    { title: "Archive 81", year: "2022", tagline: "Rewind. Replay. Reveal.", rating: "⭐ 7.3" },
    { title: "From", year: "2022-", tagline: "There's no way out.", rating: "⭐ 7.7" },
    { title: "The Terror", year: "2018-2019", tagline: "Based on a true story.", rating: "⭐ 7.9" },
    { title: "Kingdom", year: "2019-", tagline: "The dead are coming.", rating: "⭐ 8.3" },
    { title: "Supernatural", year: "2005-2020", tagline: "Saving people, hunting things.", rating: "⭐ 8.4" },
    { title: "Twin Peaks", year: "1990-1991", tagline: "Who killed Laura Palmer?", rating: "⭐ 8.8" },
    { title: "Yellowjackets", year: "2021-", tagline: "Wild.", rating: "⭐ 7.8" },
    { title: "The Haunting of Bly Manor", year: "2020", tagline: "Dead doesn't mean gone.", rating: "⭐ 7.4" },
    { title: "The Fall of the House of Usher", year: "2023", tagline: "Family is forever.", rating: "⭐ 7.9" },
    { title: "Guillermo del Toro's Cabinet of Curiosities", year: "2022", tagline: "Open your mind.", rating: "⭐ 7.0" },
    { title: "Servant", year: "2019-2023", tagline: "Doubt what you believe.", rating: "⭐ 7.4" },
    { title: "Chucky", year: "2021-", tagline: "A classic coming of rage story.", rating: "⭐ 7.3" },
    { title: "Scream Queens", year: "2015-2016", tagline: "Pretty. Evil.", rating: "⭐ 7.1" },
    { title: "Santa Clarita Diet", year: "2017-2019", tagline: "Really dead. Really funny.", rating: "⭐ 7.8" },
    { title: "Swarm", year: "2023", tagline: "Murder on the dance floor.", rating: "⭐ 7.1" },
    { title: "Brand New Cherry Flavor", year: "2021", tagline: "A spicy new limited series.", rating: "⭐ 7.2" },
    { title: "All of Us Are Dead", year: "2022-", tagline: "Survive the high school.", rating: "⭐ 7.5" }
  ],
  'Comedy': [
    { title: "The Office (US)", year: "2005-2013", tagline: "A documentary about a paper company.", rating: "⭐ 9.0" },
    { title: "Ted Lasso", year: "2020-2023", tagline: "Kindness makes a comeback.", rating: "⭐ 8.8" },
    { title: "Brooklyn Nine-Nine", year: "2013-2021", tagline: "Law without order.", rating: "⭐ 8.4" },
    { title: "Parks and Recreation", year: "2009-2015", tagline: "Bureaucracy at its best.", rating: "⭐ 8.6" },
    { title: "It's Always Sunny in Philadelphia", year: "2005-", tagline: "The gang gets weird.", rating: "⭐ 8.8" },
    { title: "Arrested Development", year: "2003-2019", tagline: "There's always money in the banana stand.", rating: "⭐ 8.7" },
    { title: "Curb Your Enthusiasm", year: "2000-", tagline: "Deeply offensive.", rating: "⭐ 8.8" },
    { title: "Fleabag", year: "2016-2019", tagline: "This is a love story.", rating: "⭐ 8.7" },
    { title: "What We Do in the Shadows", year: "2019-", tagline: "Bat!", rating: "⭐ 8.6" },
    { title: "Community", year: "2009-2015", tagline: "Six seasons and a movie!", rating: "⭐ 8.5" },
    { title: "Silicon Valley", year: "2014-2019", tagline: "Closing the loop.", rating: "⭐ 8.5" },
    { title: "Barry", year: "2018-2023", tagline: "Killin' it.", rating: "⭐ 8.4" },
    { title: "The Good Place", year: "2016-2020", tagline: "Everything is fine.", rating: "⭐ 8.2" },
    { title: "Schitt's Creek", year: "2015-2020", tagline: "Money can't buy you class.", rating: "⭐ 8.5" },
    { title: "Nathan For You", year: "2013-2017", tagline: "Good grades.", rating: "⭐ 8.9" },
    { title: "BoJack Horseman", year: "2014-2020", tagline: "Don't act like you don't know.", rating: "⭐ 8.8" },
    { title: "Rick and Morty", year: "2013-", tagline: "Wubba Lubba Dub Dub!", rating: "⭐ 9.1" },
    { title: "Veep", year: "2012-2019", tagline: "Politics is personal.", rating: "⭐ 8.3" },
    { title: "30 Rock", year: "2006-2013", tagline: "I want to go to there.", rating: "⭐ 8.3" },
    { title: "Atlanta", year: "2016-2022", tagline: "Twin peaks with rappers.", rating: "⭐ 8.6" },
    { title: "Seinfeld", year: "1989-1998", tagline: "A show about nothing.", rating: "⭐ 8.9" },
    { title: "Friends", year: "1994-2004", tagline: "I'll be there for you.", rating: "⭐ 8.9" },
    { title: "How I Met Your Mother", year: "2005-2014", tagline: "A love story in reverse.", rating: "⭐ 8.3" },
    { title: "Modern Family", year: "2009-2020", tagline: "One big (straight, gay, multi-cultural, traditional) happy family.", rating: "⭐ 8.5" },
    { title: "The Marvelous Mrs. Maisel", year: "2017-2023", tagline: "Tits up.", rating: "⭐ 8.7" },
    { title: "Only Murders in the Building", year: "2021-", tagline: "Everyone is a suspect.", rating: "⭐ 8.1" },
    { title: "Abbott Elementary", year: "2021-", tagline: "School is in session.", rating: "⭐ 8.2" },
    { title: "The Bear", year: "2022-", tagline: "Every second counts.", rating: "⭐ 8.6" },
    { title: "Succession", year: "2018-2023", tagline: "Make your move.", rating: "⭐ 8.9" },
    { title: "Scrubs", year: "2001-2010", tagline: "I'm no Superman.", rating: "⭐ 8.4" }
  ],
  'Thriller': [
    { title: "Breaking Bad", year: "2008-2013", tagline: "Respect the chemistry.", rating: "⭐ 9.5" },
    { title: "Better Call Saul", year: "2015-2022", tagline: "It's all good man.", rating: "⭐ 9.0" },
    { title: "Mindhunter", year: "2017-2019", tagline: "History is only the beginning.", rating: "⭐ 8.6" },
    { title: "True Detective (S1)", year: "2014", tagline: "Touch darkness and darkness touches you back.", rating: "⭐ 8.9" },
    { title: "Fargo", year: "2014-", tagline: "A true story.", rating: "⭐ 8.9" },
    { title: "Sherlock", year: "2010-2017", tagline: "The game is on.", rating: "⭐ 9.1" },
    { title: "Mr. Robot", year: "2015-2019", tagline: "Control is an illusion.", rating: "⭐ 8.5" },
    { title: "Ozark", year: "2017-2022", tagline: "Their last resort.", rating: "⭐ 8.5" },
    { title: "Narcos", year: "2015-2017", tagline: "Plata o Plomo.", rating: "⭐ 8.8" },
    { title: "Squid Game", year: "2021-", tagline: "45.6 Billion Won is child's play.", rating: "⭐ 8.0" },
    { title: "Dexter", year: "2006-2013", tagline: "Takes one to know one.", rating: "⭐ 8.6" },
    { title: "Money Heist", year: "2017-2021", tagline: "The perfect robbery.", rating: "⭐ 8.2" },
    { title: "Homeland", year: "2011-2020", tagline: "An American prisoner of war has been turned.", rating: "⭐ 8.3" },
    { title: "The Americans", year: "2013-2018", tagline: "All's fair in love and cold war.", rating: "⭐ 8.4" },
    { title: "Killing Eve", year: "2018-2022", tagline: "My kind of woman.", rating: "⭐ 8.1" },
    { title: "Hannibal", year: "2013-2015", tagline: "Feed your fear.", rating: "⭐ 8.5" },
    { title: "Yellowstone", year: "2018-", tagline: "Protect the family.", rating: "⭐ 8.7" },
    { title: "Peaky Blinders", year: "2013-2022", tagline: "By order of the Peaky Blinders.", rating: "⭐ 8.8" },
    { title: "Bodyguard", year: "2018", tagline: "Protect the target.", rating: "⭐ 8.1" },
    { title: "Luther", year: "2010-2019", tagline: "What is your confession?", rating: "⭐ 8.4" },
    { title: "24", year: "2001-2010", tagline: "The clock is ticking.", rating: "⭐ 8.4" },
    { title: "Prison Break", year: "2005-2017", tagline: "Break out.", rating: "⭐ 8.3" },
    { title: "Lost", year: "2004-2010", tagline: "Everything happens for a reason.", rating: "⭐ 8.3" },
    { title: "Black Mirror", year: "2011-", tagline: "The future is bright.", rating: "⭐ 8.7" },
    { title: "The Night Manager", year: "2016", tagline: "Trust no one.", rating: "⭐ 8.0" },
    { title: "Broadchurch", year: "2013-2017", tagline: "A town wrapped in secrets.", rating: "⭐ 8.4" },
    { title: "Mare of Easttown", year: "2021", tagline: "The past is never gone.", rating: "⭐ 8.4" },
    { title: "You", year: "2018-", tagline: "I'd do anything for you.", rating: "⭐ 7.7" },
    { title: "Dark", year: "2017-2020", tagline: "Everything is connected.", rating: "⭐ 8.7" },
    { title: "Severance", year: "2022-", tagline: "Work-life balance.", rating: "⭐ 8.7" }
  ],
  'Romance': [
    { title: "Normal People", year: "2020", tagline: "Not a love story.", rating: "⭐ 8.4" },
    { title: "Outlander", year: "2014-", tagline: "What if your future was the past?", rating: "⭐ 8.4" },
    { title: "Bridgerton", year: "2020-", tagline: "Love, lust, and betrayal.", rating: "⭐ 7.4" },
    { title: "This Is Us", year: "2016-2022", tagline: "This is real. This is love. This is life.", rating: "⭐ 8.7" },
    { title: "Modern Love", year: "2019-2021", tagline: "Explore love in all of its complicated and beautiful forms.", rating: "⭐ 7.9" },
    { title: "Sex Education", year: "2019-2023", tagline: "Experience is overrated.", rating: "⭐ 8.3" },
    { title: "Heartstopper", year: "2022-", tagline: "Boy meets boy.", rating: "⭐ 8.6" },
    { title: "Love", year: "2016-2018", tagline: "Love wins.", rating: "⭐ 7.7" },
    { title: "Downton Abbey", year: "2010-2015", tagline: "The war changes everything.", rating: "⭐ 8.7" },
    { title: "Poldark", year: "2015-2019", tagline: "A man of contradictions.", rating: "⭐ 8.3" },
    { title: "Fleabag", year: "2016-2019", tagline: "It's a love story.", rating: "⭐ 8.7" },
    { title: "How I Met Your Mother", year: "2005-2014", tagline: "A love story in reverse.", rating: "⭐ 8.3" },
    { title: "New Girl", year: "2011-2018", tagline: "Simply adorkable.", rating: "⭐ 7.8" },
    { title: "Gilmore Girls", year: "2000-2007", tagline: "Life's short. Talk fast.", rating: "⭐ 8.2" },
    { title: "Grey's Anatomy", year: "2005-", tagline: "Operations. Relations. Complications.", rating: "⭐ 7.6" },
    { title: "The Vampire Diaries", year: "2009-2017", tagline: "Love sucks.", rating: "⭐ 7.7" },
    { title: "Gossip Girl", year: "2007-2012", tagline: "You know you love me.", rating: "⭐ 7.5" },
    { title: "Pride and Prejudice", year: "1995", tagline: "A truth universally acknowledged.", rating: "⭐ 8.8" },
    { title: "Sense8", year: "2015-2018", tagline: "Connection is evolution.", rating: "⭐ 8.2" },
    { title: "Master of None", year: "2015-2021", tagline: "Jack of all trades.", rating: "⭐ 8.2" },
    { title: "One Day", year: "2024", tagline: "Twenty years. Two people.", rating: "⭐ 8.1" },
    { title: "The Summer I Turned Pretty", year: "2022-", tagline: "Summer love.", rating: "⭐ 7.3" },
    { title: "Emily in Paris", year: "2020-", tagline: "Frenchkissing life.", rating: "⭐ 6.9" },
    { title: "Virgin River", year: "2019-", tagline: "Start fresh.", rating: "⭐ 7.4" },
    { title: "Sweet Magnolias", year: "2020-", tagline: "Friends forever.", rating: "⭐ 7.3" },
    { title: "Fellow Travelers", year: "2023", tagline: "A decades-long romance.", rating: "⭐ 8.3" },
    { title: "Looking", year: "2014-2015", tagline: "Find something real.", rating: "⭐ 8.3" },
    { title: "Lovesick", year: "2014-2018", tagline: "In sickness and in health.", rating: "⭐ 8.0" },
    { title: "Catastrophe", year: "2015-2019", tagline: "One mistake can change everything.", rating: "⭐ 8.2" },
    { title: "Starstruck", year: "2021-", tagline: "He's a star. She's a mess.", rating: "⭐ 7.5" }
  ],
  'Anime': [
    { title: "Attack on Titan", year: "2013-2023", tagline: "Fight!", rating: "⭐ 9.1" },
    { title: "Fullmetal Alchemist: Brotherhood", year: "2009-2010", tagline: "Equivalent exchange.", rating: "⭐ 9.1" },
    { title: "Death Note", year: "2006-2007", tagline: "I am justice!", rating: "⭐ 9.0" },
    { title: "Cowboy Bebop", year: "1998-1999", tagline: "See you space cowboy...", rating: "⭐ 8.9" },
    { title: "One Piece", year: "1999-", tagline: "I'm gonna be King of the Pirates!", rating: "⭐ 8.9" },
    { title: "Steins;Gate", year: "2011", tagline: "El Psy Kongroo.", rating: "⭐ 8.8" },
    { title: "Hunter x Hunter", year: "2011-2014", tagline: "The hunt is on.", rating: "⭐ 9.0" },
    { title: "Vinland Saga", year: "2019-", tagline: "A true warrior needs no sword.", rating: "⭐ 8.8" },
    { title: "Cyberpunk: Edgerunners", year: "2022", tagline: "Fly me to the moon.", rating: "⭐ 8.3" },
    { title: "Arcane", year: "2021-", tagline: "Every legend has a beginning.", rating: "⭐ 9.0" },
    { title: "Neon Genesis Evangelion", year: "1995-1996", tagline: "God's in his heaven, all's right with the world.", rating: "⭐ 8.5" },
    { title: "Code Geass", year: "2006-2008", tagline: "The power of the king.", rating: "⭐ 8.7" },
    { title: "Mob Psycho 100", year: "2016-2022", tagline: "100% explosion.", rating: "⭐ 8.6" },
    { title: "One Punch Man", year: "2015-", tagline: "Just a guy who's a hero for fun.", rating: "⭐ 8.7" },
    { title: "Chainsaw Man", year: "2022-", tagline: "Rip and tear.", rating: "⭐ 8.4" },
    { title: "Jujutsu Kaisen", year: "2020-", tagline: "Curse your fate.", rating: "⭐ 8.5" },
    { title: "Demon Slayer", year: "2019-", tagline: "Slay the demons.", rating: "⭐ 8.6" },
    { title: "Spy x Family", year: "2022-", tagline: "For world peace.", rating: "⭐ 8.3" },
    { title: "Haikyuu!!", year: "2014-2020", tagline: "Fly high.", rating: "⭐ 8.7" },
    { title: "Monster", year: "2004-2005", tagline: "The beast inside.", rating: "⭐ 8.7" },
    { title: "Bleach: Thousand-Year Blood War", year: "2022-", tagline: "Protect the Soul Society.", rating: "⭐ 9.0" },
    { title: "Frieren: Beyond Journey's End", year: "2023-", tagline: "The adventure is over. The journey begins.", rating: "⭐ 9.1" },
    { title: "Solo Leveling", year: "2024-", tagline: "Only I level up.", rating: "⭐ 8.4" },
    { title: "Blue Lock", year: "2022-", tagline: "Be the best striker.", rating: "⭐ 8.2" },
    { title: "Violet Evergarden", year: "2018", tagline: "What does 'I love you' mean?", rating: "⭐ 8.4" },
    { title: "Erased", year: "2016", tagline: "Revival.", rating: "⭐ 8.5" },
    { title: "Parasyte: The Maxim", year: "2014-2015", tagline: "You are the only one who can save us.", rating: "⭐ 8.3" },
    { title: "Psycho-Pass", year: "2012-", tagline: "What color is your soul?", rating: "⭐ 8.2" },
    { title: "Gurren Lagann", year: "2007", tagline: "Pierce the heavens!", rating: "⭐ 8.6" },
    { title: "Samurai Champloo", year: "2004-2005", tagline: "Life, death, and hip-hop.", rating: "⭐ 8.6" }
  ],
  'Drama': [
    { title: "The Sopranos", year: "1999-2007", tagline: "Woke up this morning...", rating: "⭐ 9.2" },
    { title: "The Wire", year: "2002-2008", tagline: "It's all in the game.", rating: "⭐ 9.3" },
    { title: "Succession", year: "2018-2023", tagline: "Make your move.", rating: "⭐ 8.9" },
    { title: "Mad Men", year: "2007-2015", tagline: "Whatever you think it is, it's not.", rating: "⭐ 8.7" },
    { title: "Chernobyl", year: "2019", tagline: "What is the cost of lies?", rating: "⭐ 9.3" },
    { title: "The Crown", year: "2016-2023", tagline: "Heavy lies the head.", rating: "⭐ 8.6" },
    { title: "House of Cards", year: "2013-2018", tagline: "Bad for the greater good.", rating: "⭐ 8.6" },
    { title: "Better Call Saul", year: "2015-2022", tagline: "It's showtime.", rating: "⭐ 9.0" },
    { title: "Six Feet Under", year: "2001-2005", tagline: "Every day above ground is a good one.", rating: "⭐ 8.7" },
    { title: "The Queen's Gambit", year: "2020", tagline: "Genius. Obsession. Addiction.", rating: "⭐ 8.5" },
    { title: "Friday Night Lights", year: "2006-2011", tagline: "Clear eyes. Full hearts. Can't lose.", rating: "⭐ 8.7" },
    { title: "This Is Us", year: "2016-2022", tagline: "This is real.", rating: "⭐ 8.7" },
    { title: "BoJack Horseman", year: "2014-2020", tagline: "It gets easier.", rating: "⭐ 8.8" },
    { title: "Mr. Robot", year: "2015-2019", tagline: "Hello friend.", rating: "⭐ 8.5" },
    { title: "Euphoria", year: "2019-", tagline: "Feel something.", rating: "⭐ 8.3" },
    { title: "Shameless (US)", year: "2011-2021", tagline: "No shame.", rating: "⭐ 8.5" },
    { title: "Peaky Blinders", year: "2013-2022", tagline: "Birmingham's finest.", rating: "⭐ 8.8" },
    { title: "Downton Abbey", year: "2010-2015", tagline: "Tradition stands.", rating: "⭐ 8.7" },
    { title: "Yellowstone", year: "2018-", tagline: "Ride for the brand.", rating: "⭐ 8.7" },
    { title: "The West Wing", year: "1999-2006", tagline: "The future is here.", rating: "⭐ 8.9" },
    { title: "Billions", year: "2016-2023", tagline: "Power has a price.", rating: "⭐ 8.3" },
    { title: "Suits", year: "2011-2019", tagline: "Closers only.", rating: "⭐ 8.4" },
    { title: "Boardwalk Empire", year: "2010-2014", tagline: "Atlantic City. 1920.", rating: "⭐ 8.6" },
    { title: "Deadwood", year: "2004-2006", tagline: "A hell of a place to make your fortune.", rating: "⭐ 8.6" },
    { title: "Rome", year: "2005-2007", tagline: "The world's greatest empire.", rating: "⭐ 8.7" },
    { title: "The Bear", year: "2022-", tagline: "Every second counts.", rating: "⭐ 8.6" },
    { title: "Severance", year: "2022-", tagline: "Work-life balance.", rating: "⭐ 8.7" },
    { title: "Sons of Anarchy", year: "2008-2014", tagline: "Ride free or die.", rating: "⭐ 8.6" },
    { title: "Rectify", year: "2013-2016", tagline: "The truth will set you free.", rating: "⭐ 8.3" },
    { title: "The Leftovers", year: "2014-2017", tagline: "Let the mystery be.", rating: "⭐ 8.3" }
  ],
  'Mystery': [
    { title: "True Detective (S1)", year: "2014", tagline: "Man is the cruelest animal.", rating: "⭐ 8.9" },
    { title: "Sherlock", year: "2010-2017", tagline: "Brainy is the new sexy.", rating: "⭐ 9.1" },
    { title: "Mindhunter", year: "2017-2019", tagline: "To catch a criminal, you have to think like one.", rating: "⭐ 8.6" },
    { title: "Twin Peaks", year: "1990-1991", tagline: "Fire walk with me.", rating: "⭐ 8.8" },
    { title: "Dark", year: "2017-2020", tagline: "Everything is connected.", rating: "⭐ 8.7" },
    { title: "Severance", year: "2022-", tagline: "Work-life balance.", rating: "⭐ 8.7" },
    { title: "Lost", year: "2004-2010", tagline: "Guys... where are we?", rating: "⭐ 8.3" },
    { title: "Mare of Easttown", year: "2021", tagline: "The past is never gone.", rating: "⭐ 8.4" },
    { title: "Big Little Lies", year: "2017-2019", tagline: "A perfect life is a perfect lie.", rating: "⭐ 8.4" },
    { title: "Sharp Objects", year: "2018", tagline: "Welcome home.", rating: "⭐ 8.1" },
    { title: "Broadchurch", year: "2013-2017", tagline: "A town wrapped in secrets.", rating: "⭐ 8.4" },
    { title: "The Night Of", year: "2016", tagline: "One night can change everything.", rating: "⭐ 8.4" },
    { title: "Dexter", year: "2006-2013", tagline: "America's favorite serial killer.", rating: "⭐ 8.6" },
    { title: "Hannibal", year: "2013-2015", tagline: "Savor the hunt.", rating: "⭐ 8.5" },
    { title: "Mr. Robot", year: "2015-2019", tagline: "Our democracy has been hacked.", rating: "⭐ 8.5" },
    { title: "Black Mirror", year: "2011-", tagline: "Reflecting the dark side.", rating: "⭐ 8.7" },
    { title: "The X-Files", year: "1993-2018", tagline: "The truth is out there.", rating: "⭐ 8.6" },
    { title: "Stranger Things", year: "2016-", tagline: "Something is coming.", rating: "⭐ 8.7" },
    { title: "Only Murders in the Building", year: "2021-", tagline: "Everyone is a suspect.", rating: "⭐ 8.1" },
    { title: "Poker Face", year: "2023-", tagline: "Bullshit detector.", rating: "⭐ 7.9" },
    { title: "The Killing", year: "2011-2014", tagline: "Who killed Rosie Larsen?", rating: "⭐ 8.3" },
    { title: "The Sinner", year: "2017-2021", tagline: "Everyone has a secret.", rating: "⭐ 7.9" },
    { title: "The Outsider", year: "2020", tagline: "Believe the unbelievable.", rating: "⭐ 7.7" },
    { title: "Castle Rock", year: "2018-2019", tagline: "Fear the past.", rating: "⭐ 7.5" },
    { title: "Yellowjackets", year: "2021-", tagline: "Wild.", rating: "⭐ 7.8" },
    { title: "From", year: "2022-", tagline: "There's no way out.", rating: "⭐ 7.7" },
    { title: "Outer Range", year: "2022-", tagline: "The void is waiting.", rating: "⭐ 7.1" },
    { title: "Silo", year: "2023-", tagline: "The truth will surface.", rating: "⭐ 8.1" },
    { title: "Devs", year: "2020", tagline: "Nothing happens for a reason.", rating: "⭐ 7.7" },
    { title: "Top of the Lake", year: "2013-2017", tagline: "Paradise is hell.", rating: "⭐ 7.4" }
  ],
  'Fantasy': [
    { title: "Game of Thrones", year: "2011-2019", tagline: "Winter is coming.", rating: "⭐ 9.2" },
    { title: "House of the Dragon", year: "2022-", tagline: "Fire and Blood.", rating: "⭐ 8.4" },
    { title: "The Witcher", year: "2019-", tagline: "Destiny is a beast.", rating: "⭐ 8.0" },
    { title: "Stranger Things", year: "2016-", tagline: "One summer can change everything.", rating: "⭐ 8.7" },
    { title: "The Mandalorian", year: "2019-", tagline: "I can bring you in warm, or I can bring you in cold.", rating: "⭐ 8.7" },
    { title: "Arcane", year: "2021-", tagline: "Destiny separates.", rating: "⭐ 9.0" },
    { title: "Avatar: The Last Airbender", year: "2005-2008", tagline: "Master of all four elements.", rating: "⭐ 9.3" },
    { title: "The Legend of Korra", year: "2012-2014", tagline: "Balance.", rating: "⭐ 8.3" },
    { title: "Supernatural", year: "2005-2020", tagline: "Driver picks the music.", rating: "⭐ 8.4" },
    { title: "Buffy the Vampire Slayer", year: "1997-2003", tagline: "Into every generation a slayer is born.", rating: "⭐ 8.3" },
    { title: "Outlander", year: "2014-", tagline: "The past is waiting.", rating: "⭐ 8.4" },
    { title: "Good Omens", year: "2019-", tagline: "The end is nigh.", rating: "⭐ 8.0" },
    { title: "Lucifer", year: "2016-2021", tagline: "It's good to be bad.", rating: "⭐ 8.1" },
    { title: "His Dark Materials", year: "2019-2022", tagline: "One girl will change worlds.", rating: "⭐ 7.8" },
    { title: "Shadow and Bone", year: "2021-2023", tagline: "Summon the light.", rating: "⭐ 7.5" },
    { title: "The Sandman", year: "2022-", tagline: "Dreams never die.", rating: "⭐ 7.7" },
    { title: "Wednesday", year: "2022-", tagline: "Full of woe.", rating: "⭐ 8.1" },
    { title: "American Gods", year: "2017-2021", tagline: "You are what you worship.", rating: "⭐ 7.6" },
    { title: "Carnival Row", year: "2019-2023", tagline: "Different is dangerous.", rating: "⭐ 7.7" },
    { title: "Sweet Tooth", year: "2021-2024", tagline: "The end of the world is just the beginning.", rating: "⭐ 7.7" },
    { title: "The Wheel of Time", year: "2021-", tagline: "The wheel weaves as the wheel wills.", rating: "⭐ 7.1" },
    { title: "The Lord of the Rings: The Rings of Power", year: "2022-", tagline: "Evil does not sleep. It waits.", rating: "⭐ 6.9" },
    { title: "One Piece (Live Action)", year: "2023-", tagline: "Set sail.", rating: "⭐ 8.3" },
    { title: "Percy Jackson and the Olympians", year: "2023-", tagline: "Not all heroes wear capes.", rating: "⭐ 7.2" },
    { title: "Merlin", year: "2008-2012", tagline: "Keep the magic secret.", rating: "⭐ 7.9" },
    { title: "Once Upon a Time", year: "2011-2018", tagline: "Magic is coming.", rating: "⭐ 7.7" },
    { title: "Grimm", year: "2011-2017", tagline: "Not your usual fairy tale.", rating: "⭐ 7.8" },
    { title: "Charmed", year: "1998-2006", tagline: "The power of three.", rating: "⭐ 7.1" },
    { title: "Xena: Warrior Princess", year: "1995-2001", tagline: "The power. The passion. The danger.", rating: "⭐ 6.7" },
    { title: "Angel", year: "1999-2004", tagline: "Live fast. Die never.", rating: "⭐ 7.9" }
  ],
  'Crime': [
    { title: "Breaking Bad", year: "2008-2013", tagline: "Respect the chemistry.", rating: "⭐ 9.5" },
    { title: "The Wire", year: "2002-2008", tagline: "It's all in the game.", rating: "⭐ 9.3" },
    { title: "The Sopranos", year: "1999-2007", tagline: "Woke up this morning...", rating: "⭐ 9.2" },
    { title: "Sherlock", year: "2010-2017", tagline: "The game is on.", rating: "⭐ 9.1" },
    { title: "True Detective (S1)", year: "2014", tagline: "Touch darkness and darkness touches you back.", rating: "⭐ 8.9" },
    { title: "Better Call Saul", year: "2015-2022", tagline: "It's all good man.", rating: "⭐ 9.0" },
    { title: "Fargo", year: "2014-", tagline: "A true story.", rating: "⭐ 8.9" },
    { title: "Peaky Blinders", year: "2013-2022", tagline: "By order of the Peaky Blinders.", rating: "⭐ 8.8" },
    { title: "Mindhunter", year: "2017-2019", tagline: "History is only the beginning.", rating: "⭐ 8.6" },
    { title: "Narcos", year: "2015-2017", tagline: "Plata o Plomo.", rating: "⭐ 8.8" },
    { title: "Ozark", year: "2017-2022", tagline: "Their last resort.", rating: "⭐ 8.5" },
    { title: "Dexter", year: "2006-2013", tagline: "Takes one to know one.", rating: "⭐ 8.6" },
    { title: "Boardwalk Empire", year: "2010-2014", tagline: "Atlantic City. 1920.", rating: "⭐ 8.6" },
    { title: "Sons of Anarchy", year: "2008-2014", tagline: "Ride free or die.", rating: "⭐ 8.6" },
    { title: "The Shield", year: "2002-2008", tagline: "The road to justice is twisted.", rating: "⭐ 8.7" },
    { title: "Hannibal", year: "2013-2015", tagline: "Feed your fear.", rating: "⭐ 8.5" },
    { title: "Twin Peaks", year: "1990-1991", tagline: "Who killed Laura Palmer?", rating: "⭐ 8.8" },
    { title: "Luther", year: "2010-2019", tagline: "What is your confession?", rating: "⭐ 8.4" },
    { title: "Justified", year: "2010-2015", tagline: "Lawman.", rating: "⭐ 8.6" },
    { title: "Banshee", year: "2013-2016", tagline: "Small town. Big secrets.", rating: "⭐ 8.4" },
    { title: "Mr. Robot", year: "2015-2019", tagline: "Control is an illusion.", rating: "⭐ 8.5" },
    { title: "Money Heist", year: "2017-2021", tagline: "The perfect robbery.", rating: "⭐ 8.2" },
    { title: "Narcos: Mexico", year: "2018-2021", tagline: "The drug war has no end.", rating: "⭐ 8.4" },
    { title: "Gomorrah", year: "2014-2021", tagline: "Loyalty is a luxury.", rating: "⭐ 8.7" },
    { title: "Top Boy", year: "2011-2023", tagline: "This is our world.", rating: "⭐ 8.4" },
    { title: "Broadchurch", year: "2013-2017", tagline: "A town wrapped in secrets.", rating: "⭐ 8.4" },
    { title: "Mare of Easttown", year: "2021", tagline: "The past is never gone.", rating: "⭐ 8.4" },
    { title: "Making a Murderer", year: "2015-2018", tagline: "The truth is the only defense.", rating: "⭐ 8.6" },
    { title: "Tiger King", year: "2020", tagline: "Murder, Mayhem and Madness.", rating: "⭐ 7.5" },
    { title: "The Staircase", year: "2004-2018", tagline: "Did he do it?", rating: "⭐ 7.8" },
    { title: "The Jinx", year: "2015", tagline: "The life and deaths of Robert Durst.", rating: "⭐ 8.6" }
  ]
};
